import type { Project, TableMapping, MigrationProgress } from "./types"

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "ERP Migration",
    description: "Migrate ERP system from Oracle 19c to PostgreSQL 16",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    sourceConnection: {
      type: "oracle",
      host: "oracle-prod.company.com",
      port: 1521,
      database: "ERPDB",
      schema: "HR",
      username: "erp_admin",
      isConnected: true,
    },
    targetConnection: {
      type: "postgresql",
      host: "pg-prod.company.com",
      port: 5432,
      database: "erp_new",
      schema: "public",
      username: "pg_admin",
      isConnected: true,
    },
    tableMappings: [],
    status: "configured",
  },
  {
    id: "2",
    name: "CRM Data Migration",
    description: "Customer relationship management database migration",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-18"),
    status: "draft",
    tableMappings: [],
  },
  {
    id: "3",
    name: "Analytics DW",
    description: "Analytics data warehouse migration project",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-15"),
    status: "completed",
    tableMappings: [],
  },
]

export const mockTables: TableMapping[] = [
  {
    id: "1",
    sourceTable: "EMPLOYEES",
    sourceSchema: "HR",
    targetTable: "employees",
    targetSchema: "public",
    enabled: true,
    status: "mapped",
    columnMappings: [
      {
        id: "1",
        sourceColumn: "EMPLOYEE_ID",
        sourceDataType: "NUMBER(6)",
        targetColumn: "employee_id",
        targetDataType: "INTEGER",
        nullable: false,
        isPrimaryKey: true,
        isForeignKey: false,
      },
      {
        id: "2",
        sourceColumn: "FIRST_NAME",
        sourceDataType: "VARCHAR2(20)",
        targetColumn: "first_name",
        targetDataType: "VARCHAR(20)",
        nullable: true,
        isPrimaryKey: false,
        isForeignKey: false,
      },
      {
        id: "3",
        sourceColumn: "LAST_NAME",
        sourceDataType: "VARCHAR2(25)",
        targetColumn: "last_name",
        targetDataType: "VARCHAR(25)",
        nullable: false,
        isPrimaryKey: false,
        isForeignKey: false,
      },
      {
        id: "4",
        sourceColumn: "EMAIL",
        sourceDataType: "VARCHAR2(50)",
        targetColumn: "email",
        targetDataType: "VARCHAR(50)",
        nullable: false,
        isPrimaryKey: false,
        isForeignKey: false,
      },
      {
        id: "5",
        sourceColumn: "HIRE_DATE",
        sourceDataType: "DATE",
        targetColumn: "hire_date",
        targetDataType: "TIMESTAMP",
        nullable: false,
        isPrimaryKey: false,
        isForeignKey: false,
      },
      {
        id: "6",
        sourceColumn: "SALARY",
        sourceDataType: "NUMBER(8,2)",
        targetColumn: "salary",
        targetDataType: "NUMERIC(8,2)",
        nullable: true,
        isPrimaryKey: false,
        isForeignKey: false,
      },
      {
        id: "7",
        sourceColumn: "DEPARTMENT_ID",
        sourceDataType: "NUMBER(4)",
        targetColumn: "department_id",
        targetDataType: "INTEGER",
        nullable: true,
        isPrimaryKey: false,
        isForeignKey: true,
      },
    ],
  },
  {
    id: "2",
    sourceTable: "DEPARTMENTS",
    sourceSchema: "HR",
    targetTable: "departments",
    targetSchema: "public",
    enabled: true,
    status: "mapped",
    columnMappings: [
      {
        id: "1",
        sourceColumn: "DEPARTMENT_ID",
        sourceDataType: "NUMBER(4)",
        targetColumn: "department_id",
        targetDataType: "INTEGER",
        nullable: false,
        isPrimaryKey: true,
        isForeignKey: false,
      },
      {
        id: "2",
        sourceColumn: "DEPARTMENT_NAME",
        sourceDataType: "VARCHAR2(30)",
        targetColumn: "department_name",
        targetDataType: "VARCHAR(30)",
        nullable: false,
        isPrimaryKey: false,
        isForeignKey: false,
      },
      {
        id: "3",
        sourceColumn: "MANAGER_ID",
        sourceDataType: "NUMBER(6)",
        targetColumn: "manager_id",
        targetDataType: "INTEGER",
        nullable: true,
        isPrimaryKey: false,
        isForeignKey: true,
      },
      {
        id: "4",
        sourceColumn: "LOCATION_ID",
        sourceDataType: "NUMBER(4)",
        targetColumn: "location_id",
        targetDataType: "INTEGER",
        nullable: true,
        isPrimaryKey: false,
        isForeignKey: true,
      },
    ],
  },
  {
    id: "3",
    sourceTable: "JOBS",
    sourceSchema: "HR",
    targetTable: "jobs",
    targetSchema: "public",
    enabled: true,
    status: "pending",
    columnMappings: [
      {
        id: "1",
        sourceColumn: "JOB_ID",
        sourceDataType: "VARCHAR2(10)",
        targetColumn: "job_id",
        targetDataType: "VARCHAR(10)",
        nullable: false,
        isPrimaryKey: true,
        isForeignKey: false,
      },
      {
        id: "2",
        sourceColumn: "JOB_TITLE",
        sourceDataType: "VARCHAR2(35)",
        targetColumn: "job_title",
        targetDataType: "VARCHAR(35)",
        nullable: false,
        isPrimaryKey: false,
        isForeignKey: false,
      },
      {
        id: "3",
        sourceColumn: "MIN_SALARY",
        sourceDataType: "NUMBER(6)",
        targetColumn: "min_salary",
        targetDataType: "INTEGER",
        nullable: true,
        isPrimaryKey: false,
        isForeignKey: false,
      },
      {
        id: "4",
        sourceColumn: "MAX_SALARY",
        sourceDataType: "NUMBER(6)",
        targetColumn: "max_salary",
        targetDataType: "INTEGER",
        nullable: true,
        isPrimaryKey: false,
        isForeignKey: false,
      },
    ],
  },
  {
    id: "4",
    sourceTable: "JOB_HISTORY",
    sourceSchema: "HR",
    targetTable: "job_history",
    targetSchema: "public",
    enabled: false,
    status: "pending",
    columnMappings: [],
  },
  {
    id: "5",
    sourceTable: "LOCATIONS",
    sourceSchema: "HR",
    targetTable: "locations",
    targetSchema: "public",
    enabled: true,
    status: "pending",
    columnMappings: [],
  },
  {
    id: "6",
    sourceTable: "COUNTRIES",
    sourceSchema: "HR",
    targetTable: "countries",
    targetSchema: "public",
    enabled: true,
    status: "migrated",
    columnMappings: [],
  },
  {
    id: "7",
    sourceTable: "REGIONS",
    sourceSchema: "HR",
    targetTable: "regions",
    targetSchema: "public",
    enabled: true,
    status: "migrated",
    columnMappings: [],
  },
]

export const mockMigrationProgress: MigrationProgress = {
  projectId: "1",
  totalTables: 7,
  completedTables: 2,
  totalRows: 125000,
  migratedRows: 45000,
  currentTable: "EMPLOYEES",
  status: "running",
  startTime: new Date(Date.now() - 1000 * 60 * 15), // 15 minutes ago
  logs: [
    {
      id: "1",
      timestamp: new Date(Date.now() - 1000 * 60 * 15),
      level: "info",
      message: "Migration started",
      details: "Project: ERP Migration",
    },
    {
      id: "2",
      timestamp: new Date(Date.now() - 1000 * 60 * 14),
      level: "info",
      message: "Connected to Oracle database",
      details: "Host: oracle-prod.company.com",
    },
    {
      id: "3",
      timestamp: new Date(Date.now() - 1000 * 60 * 13),
      level: "info",
      message: "Connected to PostgreSQL database",
      details: "Host: pg-prod.company.com",
    },
    {
      id: "4",
      timestamp: new Date(Date.now() - 1000 * 60 * 12),
      level: "success",
      message: "Table REGIONS migrated successfully",
      details: "4 rows transferred",
    },
    {
      id: "5",
      timestamp: new Date(Date.now() - 1000 * 60 * 10),
      level: "success",
      message: "Table COUNTRIES migrated successfully",
      details: "25 rows transferred",
    },
    {
      id: "6",
      timestamp: new Date(Date.now() - 1000 * 60 * 8),
      level: "warning",
      message: "Data truncation detected in EMPLOYEES.EMAIL",
      details: "Some values exceed target column length",
    },
    {
      id: "7",
      timestamp: new Date(Date.now() - 1000 * 60 * 5),
      level: "info",
      message: "Processing table EMPLOYEES",
      details: "107 of 500 rows transferred",
    },
  ],
}
